title: Jia-Rui Zhang
logo: /assets/img/logo.png
description: Jia-Rui in Lake Geneva
logo: /assets/img/logo1.jpg
description: Jia-Rui in Universal Beijing Resort
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
